# PRACTICA 1:   SCRIPT EN SPYDER, LIBRERÍA NUMPY, NUMEROS COMPLEJOS, FUNCIONES TRIGONOMÉTRICAS Y ARREGLOS.
 
## INTRODUCCIÓN

Para hacer esta práctica, se asumirá que ha leído todo el material introductorio de Python, sintaxis básica, librerías y manejo de Jupyter Notebook. Si tiene alguna duda, puede resolverla buscando la información en los documentos anteriormente suministrados.
	
## OBJETIVOS

    1. Conocer los principios básicos de operación de Python.
    2. Aprender a crear scripts usando el menú y las ventanas de Spyder.
    3. Importar la librería NumPy. 
    4. Manejar funciones trigonométricas básicas, números complejos y funciones varias (sign).
    5. Crear, acceder y manipular  arreglos
    6. Entender las estructuras condicionales de control de flujo
    7. Generar una señal sinusoidal

## PARTE EXPERIMENTAL
En Spyder cree un nuevo archivo llamado `Practica_1_SyS.py`.  
Vaya creando sectores o celdas con las instrucciones que se irán colocando en este enunciado. Usando `#%%` separa las celdas o grupos. Ejecútelas para **verificar** su *funcionamiento*.

Comenzaremos importando la librería NumPy.

In [2]:
import numpy as np   # numpy se usa para la manipulación de vectores y matrices

### Números complejos

Se genera el número complejo $2+3j$ de 2 formas diferentes. Se pueden representar números complejos usando la letra $i$ o la letra $j$

In [4]:
zc1 = 2+3j
zc2 = complex(2,3)

Se imprime en pantalla la pregunta de si las 2 representaciones representan al mismo número y se plantea la comparación de las dos variable `zc1` y `zc2`.

In [5]:
print('zc1 = zc2? ', (zc1 == zc2))

zc1 = zc2?  True


Se determinanla parte real, la parte imaginaria, la magnitud, la fase (en radianes) y el complejo conjugado de `zc1`, y se almacenan en diversas variables.

In [6]:
zc1_real = np.real(zc1)
zc1_imag = np.imag(zc1)
zc1_abs = np.abs(zc1)
zc1_angulo = np.angle(zc1)
zc1_conj = np.conj(zc1)

Se imprimen todas esas nuevas variables

In [7]:
print(zc1)
print('parte real: ', zc1_real)
print('parte imaginaria: ', zc1_imag)
print('valor absoluto: ', zc1_abs)
print('angulo en radianes: ', zc1_angulo)
print('complejo conjugado: ', zc1_conj)

(2+3j)
parte real:  2.0
parte imaginaria:  3.0
valor absoluto:  3.605551275463989
angulo en radianes:  0.982793723247329
complejo conjugado:  (2-3j)


### ARREGLOS, MATRICES, VECTORES

Creamos un arreglo (matriz de 2x3) usando la función `np.array`

In [9]:
c = np.array([[1, 5, 2],[3, 4, 8]])

Se determina y almacena su traspuesta

In [10]:
c_traspuesta = np.transpose(c)

Se imprimen. El caracter `\n` sirve para generar un salto de línea

In [11]:
print('matriz c: \n', c)
print('matriz c traspuesta: \n', c_traspuesta)

matriz c: 
 [[1 5 2]
 [3 4 8]]
matriz c traspuesta: 
 [[1 3]
 [5 4]
 [2 8]]


Accederemos a la segunda fila de esta matriz

In [14]:
F2 = c[1,:]
print('Accediendo a valores en la matriz:')
print('Segunda fila:')
print(F2)

Accediendo a valores en la matriz:
Segunda fila:
[3 4 8]


### ARREGLOS, LISTAS, VECTORES

Creamos un array(vector) basado en una lista

In [15]:
x = [1, 2, 3, 4]    # esto es una lista
x = np.array([1,2,3,4])  # se crea el  array usando una lista
print('Array o vector: ')
print(x)

Array o vector: 
[1 2 3 4]


Accedemos a determinados valores 

In [17]:
c = x[0]
c = x[0]; d = x[2]; e = x[-1] # defino varias variables en la misma línea
# Observe que el último término se accede con el índice -1
# Se imprimen
print('Accediendo a valores en el vector:')
print(c, d, e)

Accediendo a valores en el vector:
1 3 4


### OPERACIONES PUNTO A PUNTO

Las operaciones matemáticas entre arrays son elemento a elemento por defecto

In [20]:
a = np.array([1,2,3,4])
b = np.array([3,4,5,6])

In [21]:
print(a*b)

[ 3  8 15 24]


### EXPONENCIACION

La exponenciación puede ser elemento a elemento o matricial (y en este caso hay que cuidar las dimensiones)

In [ ]:
a = np.array([[1,2],[3,4]])
b = a**2  # el operador de exponenciacion es **(cada elemento  al cuadrado)
c = 2**a  # matriz con 2 elevado a c/u de los elementos de la matriz
print('matriz a: \n', a)
print('matriz b: \n', b)
print('matriz c: \n', c)

## OPERACIONES UTILES

Redondeo: `round(x)`

Truncado: `fix(x)`

In [23]:
x = np.array([[2.12, 3.65],[-3.17, -3.61]])
xr1 = np.round(x)  # redondea al entero más cercano
xr2 = np.round(x, 1)  # redondea con 1 decimal
print('Redondeo a entero: \n', xr1)
print('Redondeo con 1 decimal: \n', xr2)
x_trunca = np.fix(x)
print('x truncado: \n', x_trunca)

Redondeo a entero: 
 [[ 2.  4.]
 [-3. -4.]]
Redondeo con 1 decimal: 
 [[ 2.1  3.6]
 [-3.2 -3.6]]
x truncado: 
 [[ 2.  3.]
 [-3. -3.]]


Redondeo hacia arriba y hacia abajo:
`floor(x)`, `ceil(x)`: Redondea los elementos de x a los enteros mas cercanos por debajo o por arriba

In [24]:
x_floor = np.floor(x)
x_ceil = np.ceil(x)

print('redondeo hacia abajo: \n', x_floor)
print('redondeo hacia arriba: \n', x_ceil)

redondeo hacia abajo: 
 [[ 2.  3.]
 [-4. -4.]]
redondeo hacia arriba: 
 [[ 3.  4.]
 [-3. -3.]]


Media: `np.mean(x)`

Mínimo: `np.min(x)`

Máximo: `np.max(x)`

In [25]:
media_x = np.mean(x)
min_x = np.min(x)
max_x = np.max(x)

print('Media de x: ', media_x)
print('Minimo de x: ', min_x)
print('Maximo de x: ', max_x)

Media de x:  -0.25250000000000006
Minimo de x:  -3.61
Maximo de x:  3.65


Sumatoria y producto de los elementos de x:

`np.sum(x)`

`np.prod(x)`

In [27]:
sum_x = np.sum(x)
prod_x = np.prod(x)

print('Sumatoria columnas x: ', sum_x)
print('Producto columnas x: ', prod_x)

Sumatoria columnas x:  -1.0100000000000002
Producto columnas x:  88.55135059999999


### ESTRUCTURAS DE CONTROL DE FLUJO

#### Estructuras condicionales

Las estructuras de control condicionales, son aquellas que nos **permiten evaluar si una o más condiciones se cumplen**, para decir qué acción vamos a ejecutar. 

Un ejemplo clásico es solicitar un número al usuario. Luego se analiza si este es número es > o < que cero.

Usaremos la instrucción `input` que permite que el usuario ingrese elementos por teclado. **Todo** lo que ingrese será visto como un caracter o una cadena de caracteres (string). Si se espera un número entero se usa la instrucción `int`, si se espera un número real (punto flotante) se usa la instrucción `float`. Finalmente, el resultado del `input` y su conversión, se almacena en la variable `x`.

In [30]:
x = float (input('Escribe un número'))    # Se le pide al usuario que ingrese un número.
if x > 0:  #se pregunta por una condición cuya respuesta es True o False
    print (x, ' es un número positivo')  # esto se ejecutaría si es True (la indentación es automática)
else:			# esto se ejecutaría si es False 
    print (x, ' es un número negativo')

Escribe un número -.3


-0.3  es un número negativo


#### Estructura condicional:  IF-ELSE-ELIF

Si hay más de dos posibilidades se usa `elif`, en este caso se agrega una nueva condición.

In [32]:
x = float (input('Escribe el número 1: '))
y = float (input('Escribe el número 2: '))
if x < y:
    print('x es menor que y')
elif x > y:
    print('x es mayor que y')
else:
    print('x e y son iguales')

Escribe el número 1:  4
Escribe el número 2:  3


x es mayor que y


### Estructuras de control iterativas 

A diferencia de las estructuras de control condicionales, las iterativas (también llamadas cíclicas o bucles), nos **permiten ejecutar un mismo código, de manera repetida, mientras se cumpla una condición**.

En Python se dispone de dos estructuras cíclicas:

* El bucle `while`.
* El bucle `for`.

#### Estructura iterativa: WHILE

Otra estructura que controla el flujo del programa es while, que siempre va acompañada de la verificación de una condición, ya que genera un lazo que se repite hasta que deje de cumplirse la condición. En el próximo script, se calcula el factorial de un número entero x que ingresará por teclado.

In [33]:
x = float (input('Escribe un número'))
x1 = x    # se almacena x en otra variable para poder usarla en el print final
factorial=1    ## Se inicializa el resultado factorial en 1
while x > 0:      # Hasta que x sea mayor que 0 se calcula n*(n-1) y se decrementa x
    factorial=factorial*x
    x= x-1
print ('factorial de', x1,'es =', factorial)

Escribe un número 5


factorial de 5.0 es = 120.0


#### Estructura iterativa: FOR

In [38]:
x = [1,2,3,4,9,8,7,6]  # esto es una lista. Se quiere ir imprimiendo cada elemento de x y multiplicar ese elemento por 3
i = 0
for n in x:
    x[i] = 3*x[i] 
    i = i+1
    print(n) 
print(x)

1
2
3
4
9
8
7
6
[3, 6, 9, 12, 27, 24, 21, 18]


### Generación de sinusoide
Definiremos la distancia entre muestras como $ T =0.01 seg $.
Luego construiremos un vector de tiempo entre -1 y 1, en pasos de $T$
Finalmente generaremos una sinusoide de amplitud 2 y frecuencia de 5 Hz y la graficaremos

In [ ]:
import matplotlib.pyplot as plt

T=0.01
t = np.arange(-1,1+T,T)  # Se genera un vector de tiempo entre -1 y 1
x=2*np.sin(2*np.pi*5*t); # se genera un coseno de 5 Hz
plt.plot(t,x,"-r")
plt.grid()